# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Google-SiteMap
version:      1.00
version_from: lib/WWW/Google/SiteMap.pm
installdirs:  site
requires:
    IO::File:                      0
    XML::Twig:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
